version: '3'
services:
  frontend:
    image: rusty-weather-frontend
    build: ./frontend/
    restart: always
    ports:
      - 2468:2468
    networks:
      - frontendnw
  backend:
    image: rusty-weather-backend
    build: ./backend/
    restart: always
    environment:
      - OPEN_WEATHER_API_KEY=%PLACEHOLDER_OPEN_WEATHER_API_KEY%
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
    networks:
      - frontendnw
networks:
  frontendnw:
    driver: bridge
