name: Build an test rust backend

on:
  push:
    branches-ignore:
      - "main"

defaults:
  run:
    working-directory: ./backend/

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check format
        run: |
          cargo fmt --all -- --check

      - name: Check lint
        run: |
          echo "TODO"
#          cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose


  build_rpi:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        run: |
          rustup target add armv7-unknown-linux-gnueabihf
          cargo install cross

      - name: Build rust backend
        run: |
          cross build --release --target=armv7-unknown-linux-gnueabihf
