name: Create release for Raspberry Pi

on:
  push:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

# Write permissions are required to upload the release asset.
permissions: write-all

jobs:

  build_backend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install rust toolchain
        run: |
          rustup target add armv7-unknown-linux-gnueabihf
          cargo install cross

      - name: Build rust backend
        run: |
          cd ./backend/
          cross build --release --target=armv7-unknown-linux-gnueabihf

      - name: Upload rust backend executable
        uses: actions/upload-artifact@v3
        with:
          name: rusty-weather-backend
          path: ./backend/target/armv7-unknown-linux-gnueabihf/release/rusty-weather

  build_frontend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 20.8.0

      - name: Build react frontend
        run: |
          cd ./frontend/
          npm ci
          npm run build --omit=dev

      - name: Upload react frontend build
        uses: actions/upload-artifact@v3
        with:
          name: rusty-weather-frontend
          path: ./frontend/build/*

  create_release:

    runs-on: ubuntu-latest

    needs:
      - build_backend
      - build_frontend

    steps:

      - name: Download rust backend executable from artifacts
        uses: actions/download-artifact@v3
        with:
          name: rusty-weather-backend

      - name: Download react frontend from artifacts
        uses: actions/download-artifact@v3
        with:
          name: rusty-weather-frontend

      - name: List files
        run: |
          ls -al
          ls -al backend
          ls -al frontend

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}-${{ github.run_number }}
          release_name: Release ${{ github.ref }}-${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload release asset (rust backend)
        uses: actions/upload-release-asset@v1
        id: upload-release-asset-backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rusty-weather-backend
          asset_name: rusty-weather-backend
          asset_content_type: text/plain

      - name: Upload release asset (react frontend)
        uses: actions/upload-release-asset@v1
        id: upload-release-asset-frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rusty-weather-frontend
          asset_name: rusty-weather-frontend
          asset_content_type: application/zip