name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

  build_rpi:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        run: |
          rustup target add armv7-unknown-linux-gnueabihf
          cargo install cross

      - name: Build
        run: cross build --release --target=armv7-unknown-linux-gnueabihf

      - name: List files
        run: |
          ls -al
          ls -al target/

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: rusty-weather
          path: target/armv7-unknown-linux-gnueabihf/release/rusty-weather
