name: Create release for Raspberry Pi

on:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - closed
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

# Write permissions are required to upload the release asset.
permissions: write-all

jobs:

  build_rpi:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        run: |
          rustup target add armv7-unknown-linux-gnueabihf
          cargo install cross

      - name: Build
        run: cross build --release --target=armv7-unknown-linux-gnueabihf

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: rusty-weather
          path: target/armv7-unknown-linux-gnueabihf/release/rusty-weather

  create_release:

    runs-on: ubuntu-latest

    needs: build_rpi

    steps:

      - name: Download executable from artifacts
        uses: actions/download-artifact@v3
        with:
          name: rusty-weather

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref }}-${{ github.run_number }}
          release_name: Release ${{ github.ref }}-${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        id: upload-release-asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./rusty-weather
          asset_name: rusty-weather
          asset_content_type: text/plain